name: Daily Feature Pipeline

# Trigger the workflow to run every day
on:
  schedule:
    - cron: "0 12 * * *" # This cron syntax means "at minute 0 of every hour"
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  run-feature-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          environment-file: environment.yml
          python-version: "3.11"

      - name: Run feature pipeline script
        shell: bash
        run: conda run -n aqi-prod-env python feature_pipeline.py
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
