name: Daily Feature Pipeline

# Trigger the workflow to run every day
on:
  schedule:
    - cron: "0 12 * * *" # This cron syntax means "at minute 0 of every hour"
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  run-feature-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install "hopsworks[python]"
          pip install -r requirements.txt
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}

      - name: Run feature pipeline script
        run: python feature_pipeline.py
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
